#!/usr/bin/env bash
# Mechanical doc checks that kept needing an agent audit to catch: a reference to
# an ADR that does not exist, narrative that crept back into code comments, and
# names of things that were removed or misspelt. Usage: docs-check <repo-root>.
set -euo pipefail

root=${1:?usage: docs-check <repo-root>}
cd "$root"
failed=0
fail() {
  echo "docs-check: $*" >&2
  failed=1
}

# docs/options.md is generated by CI from the option descriptions, so it is
# never scanned. PLAN.md and the ADRs are historical records.
mapfile -t ref_files < <(
  find README.md PLAN.md docs examples nixosModule tests -type f \
    \( -name '*.md' -o -name '*.nix' \) ! -path docs/options.md
)
mapfile -t living_files < <(
  find README.md docs/architecture.md examples nixosModule tests -type f \
    \( -name '*.md' -o -name '*.nix' \)
)

adr_exists() {
  local f
  for f in docs/decisions/"$1"-*.md; do
    [ -e "$f" ] && return 0
  done
  return 1
}

# 1. docs/decisions/NNNN-name.md paths (and the short docs/decisions/NNNN/NNNN
#    form) must point at an ADR that exists.
while IFS= read -r hit; do
  file=${hit%%:*}
  rest=${hit#*:}
  line=${rest%%:*}
  match=${rest#*:}
  tail=${match#docs/decisions/}
  if [[ $tail == *.md ]] && [ ! -f "$match" ]; then
    fail "$file:$line: $match does not exist"
  fi
  for n in $(grep -oE '(^|/)[0-9]{4}' <<<"$tail" | tr -d /); do
    adr_exists "$n" || fail "$file:$line: no ADR numbered $n (from $match)"
  done
done < <(grep -HnoE 'docs/decisions/[0-9]{4}(/[0-9]{4})*(-[a-z0-9-]+\.md)?' "${ref_files[@]}" || true)

# 2. "ADR NNNN" must name an ADR that exists.
while IFS= read -r hit; do
  n=$(grep -oE '[0-9]{4}' <<<"$hit" | tail -n1)
  adr_exists "$n" || fail "${hit%%:*}: no ADR numbered $n (${hit#*:})"
done < <(grep -HoE 'ADRs? [0-9]{4}' "${ref_files[@]}" || true)

# 3. Change-narrative belongs in git history and the ADRs, not in comments and
#    user-facing docs.
if grep -HnE 'Phase [0-9]+|fresh[- ]agent' "${living_files[@]}"; then
  fail "phase/audit narrative in comments or docs (see lines above); keep only the causal fact"
fi

# 4. Names of things that were removed or misspelt. vmauth's backend TLS flags
#    are -backend.TLSCAFile/TLSCertFile/TLSKeyFile (capital TLS): the lowercase
#    spelling made vmauth refuse to start.
mapfile -t no_plan_files < <(printf '%s\n' "${ref_files[@]}" | grep -v '^PLAN.md$')
if grep -HnE 'dummyClientCert|-backend\.tls(CA|Cert|Key)' "${no_plan_files[@]}"; then
  fail "reference to a removed or misspelt name (see lines above)"
fi

exit "$failed"
